# Generated by Django 5.2.4 on 2025-11-13 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.JSONField(help_text='Full workflow graph structure: nodes, edges, metadata')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if this is the active version for the workflow')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workflow.workflows')),
            ],
            options={
                'ordering': ['workflow', '-version'],
                'indexes': [models.Index(fields=['workflow', '-version'], name='workflow_wo_workflo_893388_idx'), models.Index(fields=['workflow', 'is_active'], name='workflow_wo_workflo_598fd0_idx')],
                'unique_together': {('workflow', 'version')},
            },
        ),
    ]
