# Generated by Django 5.2.4 on 2025-09-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('base_url', models.URLField()),
            ],
            options={
                'unique_together': {('system', 'service')},
            },
        ),
    ]
