# Generated by Django 5.2.4 on 2025-11-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, max_length=20, null=True)),
                ('original_ticket_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('ticket_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('source_service', models.CharField(db_index=True, default='ticket_service', max_length=50)),
                ('employee', models.JSONField(blank=True, null=True)),
                ('employee_cookie_id', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(blank=True, choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], db_index=True, default='Low', max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('Open', 'Open'), ('On Process', 'On Process'), ('On Hold', 'On Hold'), ('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], db_index=True, default='New', max_length=20, null=True)),
                ('department', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('asset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('issue_type', models.CharField(blank=True, max_length=100, null=True)),
                ('other_issue', models.TextField(blank=True, null=True)),
                ('performance_start_date', models.DateField(blank=True, null=True)),
                ('performance_end_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('rejected_by', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_items', models.JSONField(blank=True, null=True)),
                ('requested_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fiscal_year', models.CharField(blank=True, max_length=10, null=True)),
                ('department_input', models.TextField(blank=True, null=True)),
                ('dynamic_data', models.JSONField(blank=True, default=dict)),
                ('response_time', models.DurationField(blank=True, null=True)),
                ('resolution_time', models.DurationField(blank=True, null=True)),
                ('time_closed', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_task_allocated', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['original_ticket_id'], name='tickets_wor_origina_801822_idx'), models.Index(fields=['ticket_number'], name='tickets_wor_ticket__059118_idx'), models.Index(fields=['source_service'], name='tickets_wor_source__e71823_idx'), models.Index(fields=['status'], name='tickets_wor_status_6eae60_idx'), models.Index(fields=['priority'], name='tickets_wor_priorit_9c52b1_idx'), models.Index(fields=['employee'], name='tickets_wor_employe_4327d8_idx'), models.Index(fields=['department'], name='tickets_wor_departm_e8afbb_idx'), models.Index(fields=['asset_name'], name='tickets_wor_asset_n_16b3d9_idx'), models.Index(fields=['serial_number'], name='tickets_wor_serial__2dadb4_idx'), models.Index(fields=['employee_cookie_id'], name='tickets_wor_employe_b4826d_idx')],
            },
        ),
    ]
