# Generated by Django 5.2.1 on 2025-11-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_workflowticket_tickets_wor_status_6eae60_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowticket',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workflowticket',
            name='subcategory',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
