# Generated by Django 5.2.1 on 2025-11-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_workflowticket_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowticket',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workflowticket',
            name='asset_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workflowticket',
            name='cost_items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowticket',
            name='department_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowticket',
            name='dynamic_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workflowticket',
            name='employee_cookie_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowticket',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowticket',
            name='fiscal_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workflowticket',
            name='issue_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workflowticket',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workflowticket',
            name='other_issue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowticket',
            name='performance_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowticket',
            name='performance_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowticket',
            name='rejected_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workflowticket',
            name='requested_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='workflowticket',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workflowticket',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workflowticket',
            name='ticket_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='workflowticket',
            index=models.Index(fields=['ticket_number'], name='tickets_wor_ticket__059118_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowticket',
            index=models.Index(fields=['asset_name'], name='tickets_wor_asset_n_16b3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowticket',
            index=models.Index(fields=['serial_number'], name='tickets_wor_serial__2dadb4_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowticket',
            index=models.Index(fields=['employee_cookie_id'], name='tickets_wor_employe_b4826d_idx'),
        ),
    ]
