# Generated by Django 5.2.1 on 2025-11-07 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_commentrating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('file_path', models.FileField(upload_to='comments/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by_user_id', models.CharField(max_length=255)),
                ('uploaded_by_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('attached_by_user_id', models.CharField(max_length=255)),
                ('attached_by_name', models.CharField(max_length=255)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='comments.comment')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_attachments', to='comments.documentstorage')),
            ],
            options={
                'ordering': ['-attached_at'],
                'unique_together': {('comment', 'document')},
            },
        ),
    ]
