# Generated by Django 5.2.4 on 2025-11-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_documentstorage_commentdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentstorage',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentstorage',
            name='image_ratio',
            field=models.FloatField(blank=True, help_text='Width/Height ratio', null=True),
        ),
        migrations.AddField(
            model_name='documentstorage',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentstorage',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
    ]
