# Generated by Django 5.2.4 on 2025-10-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='user_id',
            field=models.UUIDField(blank=True, help_text='User ID from auth service (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='notificationrequest',
            name='user_id',
            field=models.UUIDField(blank=True, help_text='User ID from requesting service (optional)', null=True),
        ),
    ]
