# Generated by Django 5.2.4 on 2025-10-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationlog_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='user_id',
            field=models.UUIDField(blank=True, help_text='User ID from auth service', null=True),
        ),
    ]
