# Generated by Django 5.2.4 on 2025-10-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappnotification',
            name='user_id',
            field=models.IntegerField(help_text='User ID from auth service'),
        ),
    ]
