# Generated by Django 5.2.4 on 2025-11-10 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0002_steptransition_name_alter_steps_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='steptransition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steptransition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
