# Generated by Django 5.2.4 on 2025-11-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0003_steptransition_created_at_steptransition_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='design',
            field=models.JSONField(blank=True, default=dict, help_text='Store design coordinates {x, y} for frontend positioning'),
        ),
    ]
