# Generated by Django 5.2.4 on 2025-11-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0005_steptransition_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='steps',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
    ]
