# Generated by Django 5.2.1 on 2025-11-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0006_steps_is_end_steps_is_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
