# Generated by Django 5.2.4 on 2025-11-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0007_steps_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
