# Generated by Django 5.2.4 on 2025-11-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0009_alter_steps_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
        ),
    ]
