# Generated by Django 5.2.4 on 2025-11-13 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('workflow', '0002_workflowversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workflow_version',
            field=models.ForeignKey(blank=True, help_text='The specific version of the workflow used for this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workflow.workflowversion'),
        ),
    ]
