# Generated by Django 5.2.4 on 2025-11-18 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_roleusers_user_full_name'),
        ('task', '0002_task_workflow_version'),
    ]

    operations = [
        # First, remove the old unique constraint
        migrations.AlterUniqueTogether(
            name='taskitem',
            unique_together=set(),
        ),
        # Remove old fields
        migrations.RemoveField(
            model_name='taskitem',
            name='email',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='role',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='username',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='user_id',
        ),
        # Add new field
        migrations.AddField(
            model_name='taskitem',
            name='role_user',
            field=models.ForeignKey(help_text='Link to RoleUsers for user and role info', on_delete=django.db.models.deletion.CASCADE, to='role.roleusers'),
            preserve_default=False,
        ),
        # Add new unique constraint
        migrations.AlterUniqueTogether(
            name='taskitem',
            unique_together={('task', 'role_user')},
        ),
    ]
