# Generated by Django 5.2.4 on 2025-11-10 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_delete_roundrobin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='users',
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('task_item_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_id', models.IntegerField(help_text='User ID from auth service')),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('acted', 'Acted')], default='assigned', help_text="Status of this user's assignment", max_length=50)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('status_updated_on', models.DateTimeField(blank=True, null=True)),
                ('acted_on', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
            options={
                'ordering': ['assigned_on'],
                'unique_together': {('task', 'user_id')},
            },
        ),
    ]
