# Generated by Django 5.2.4 on 2025-11-10 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0002_steptransition_name_alter_steps_name'),
        ('task', '0006_remove_task_users_taskitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='acted_on_step',
            field=models.ForeignKey(blank=True, help_text='The step where the user acted on this task', null=True, on_delete=django.db.models.deletion.SET_NULL, to='step.steps'),
        ),
    ]
