# Generated by Django 5.2.4 on 2025-11-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_taskitem_name_alter_taskitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='resolution_time',
            field=models.DateTimeField(blank=True, help_text='Actual date and time when the task was resolved', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='target_resolution',
            field=models.DateTimeField(blank=True, help_text='Target date and time for task resolution', null=True),
        ),
    ]
