# Generated by Django 5.2.4 on 2025-11-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_message_deleted_by_message_deleted_by_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='ticket',
            new_name='ticket_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='edited_by_email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_full_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='closed_by_email',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='created_by_email',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='created_by_full_name',
        ),
    ]
