# Generated by Django 5.2.4 on 2025-11-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_ticket_message_ticket_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
